[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F030F4Px"

[build]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"

[profile.release]
debug = 2
lto = true      # Link-time-optimizations for further size reduction

[profile.dev]
opt-level = "z"
debug = 2
lto = true      # Link-time-optimizations for further size reduction
