[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F030F4Px"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"

[profile.release]
opt-level = "z"
lto = true      # Link-time-optimizations for further size reduction

[profile.dev]
opt-level = "s"
debug = 2